#версия спецификации докера
version: '3.9'

#прописываем сервисы
services:
  mysql:
    image: 'mysql:8.0.33'
    # переменные окружения
    environment:
      - MYSQL_ROOT_PASSWORD=root
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/spring_work_web
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/spring_work_web?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "3306:33060"
    container_name: database

  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - JAVA_VERSION=11.0.19

    container_name: 'java-app'
    ports:
      - "8080:8080"
    depends_on:
      - mysql

